version: '3'

services:
  web: &web_base
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_HOST=minio
      - AWS_ENDPOINT=http://minio:9000
      - AWS_BUCKET_NAME=rails-7-hotwire-dev
      - BUNDLE_PATH=/usr/local/bundle
      - EDITOR=vim
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_MASTER_KEY
      - REDIS_URL=redis://redis:6379

    ports:
      - 80:3000
      - 443:3001
      - 8808:8808

    container_name: web
    volumes:
      - .:/rails-7-hotwire:cached
      - bundle:/usr/local/bundle:cached
      - dummy:/rails-7-hotwire/vendor
      - dummy:/rails-7-hotwire/log
      - dummy:/rails-7-hotwire/.git

    depends_on:
      - redis

    tty: true
    stdin_open: true

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001

    container_name: minio
    volumes:
      - s3-data:/export

    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

    command: server /export --console-address ':9001'

  worker:
    <<: *web_base
    command: bundle exec sidekiq -q default -q mailers
    ports: []
    container_name: worker

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379

    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  s3-data:
    driver: local

  redis-data:
    driver: local

  bundle:
    driver: local

  packs:
    driver: local

  dummy:
